name: fetch_market_data
on:
  schedule:
    - cron: "15 7 * * 1-5"     # 每个工作日 07:15 UTC 跑
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r maxima-mvp-risk-demo/requirements.txt
      - name: Fetch Yahoo data
        env:
          TICKERS: "AAPL,MSFT,GOOGL,AMZN,META,NVDA,TSLA,SPY,QQQ,TLT,IEF,GLD"
        run: |
          python maxima-mvp-risk-demo/scripts/fetch_market.py \
            --out maxima-mvp-risk-demo/data/market_latest.csv \
            --start 2018-01-01 --incremental
      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add maxima-mvp-risk-demo/data/market_latest.csv
          git commit -m "auto: update market data" || echo "No changes"
          git push
